let express = require("express");
let router = express.Router();
let user = require("./API/user");
let login = require("./API/login");
let post = require("./API/post");
let comment = require("./API/comment");
let signUp = require("./API/signUp");
let home = require("./API/home");
let friendship = require("./API/friendship");
let search = require("./API/search");
router.get("/user", user.get);
router.get("/post", post.get);
router.get("/comment", comment.get);
router.get("/home", home.get);
router.get("/friendship", friendship.get);
router.get("/search", search.get);
router.post("/login", login.post);
router.post("/signUp", signUp.post);
router.post("/post", post.post);
router.post("/comment", comment.post);
router.post("/home", home.post);
router.post("/friendship", friendship.post);
module.exports = router;
